### ISSUE TITLE
Number of matches reported in fit does not match number of reference sources in fit

### ISSUE THREAD

**Issue by stsci-hack** [spacetelescope/tweakwcs#149]
The reported fit from tweakwcs includes parameters for the number of matches and the magnitudes (RA and Dec, as well) of the reference sources used in the fit.  Naively, one would assume that for the final fit, those two values would agree, since the information about the reference sources used reflects the final solution after trimming for outliers.  An example of this type of inconsistency can be seen in: 

```
#  FIT being reported for hst_13767_2p_wfc3_ir_f160w_icph2pg0_flt.fits
{'status': 'SUCCESS', 'fitgeom': 'rscale', 'eff_minobj': 4, 'matrix': array([[ 1.00018051e+00,  1.54133188e-04],
       [-1.54133188e-04,  1.00018051e+00]], dtype=float64), 'shift': array([-0.54684071,  0.37861338]), 'center': array([671.63590533, 287.1062635 ]), 'fitmask': array([ True, False, False,  True]), 'proper_rot': 0.008829587250928484, 'proper': True, 'rot': (0.008829587250928484, 0.008829587250928484), '<rot>': 0.008829587250928484, 'scale': (1.0001805207884638, 1.0001805207884638), '<scale>': 1.0001805207884638, 'skew': 0.0, 'rmse': 0.0076114489222678435, 'mae': 0.0076114489222678435, 'fit_RA': array([148.31433827, 148.33204428]), 'fit_DEC': array([51.90442671, 51.89867556]), 'nmatches': 4, 'matched_ref_idx': array([1, 4, 3, 0], dtype=uint64), 'matched_input_idx': array([2, 0, 1, 3], dtype=uint64), 'FIT_RMS': 1.137815686114152e-08, 'TOTAL_RMS': 2.27060774536552e-08, 'NUM_FITS': 4, 'RMS_RA': <Angle 2.02836694e-05 mas>, 'RMS_DEC': <Angle 0.00012285 mas>, 'catalog': 'GAIAeDR3', 'input_mag': <Column name='mag' dtype='float64' length=2>
-4.415791442510083
-2.870860271276621, 'ref_mag': <Column name='mag' dtype='float64' length=2>
20.95486
21.12648}
```

Trying to rely on 'nmatches' (or even 'NUM_FITS') is impossible since it does not accurately reflect what was used for the fit actually being returned for use.  These values are ultimately desired to try to screen for suspicious fits where too few matches end up being used resulting in unrealistic fits, such as seen here for the same exposure with different fitting parameters/reference sources:

```
{'status': 'SUCCESS', 'fitgeom': 'rscale', 'eff_minobj': 4, 'matrix': array([[-0.33807193,  0.94112683],
       [ 0.94112683,  0.33807193]], dtype=float64), 'shift': array([ 691.5095016 , -485.81309321]), 'center': array([671.64594639, 286.82108173]), 'fitmask': array([ True, False, False,  True]), 'proper_rot': 109.75932182741576, 'proper': False, 'rot': (-109.75932182741576, 70.24067817258425), '<rot>': -19.759321827415754, 'scale': (1.0000061706878065, 1.0000061706878065), '<scale>': 1.0000061706878065, 'skew': -180.0, 'rmse': 3.134230418800277e-14, 'mae': 1.9172112421352957e-14, 'fit_RA': array([148.31433873, 148.33204473]), 'fit_DEC': array([51.90442676, 51.8986756 ]), 'nmatches': 4, 'matched_ref_idx': array([1, 4, 3, 0], dtype=uint64), 'matched_input_idx': array([120, 202, 119, 122], dtype=uint64), 'FIT_RMS': 5.101507707318976e-08, 'TOTAL_RMS': 5.101507707318976e-08, 'NUM_FITS': 1, 'RMS_RA': <Angle 0. mas>, 'RMS_DEC': <Angle 4.0074989e-08 mas>, 'catalog': 'GAIAeDR3', 'input_mag': <Column name='mag' dtype='float64' length=2>
-4.031898139465059
-2.891582967763686, 'ref_mag': <Column name='mag' dtype='float64' length=2>
20.95486
21.12648}
```
This is unrealistic (bad) as evidenced by ROT of -19.759 degrees and shift being larger than 1/2 the field of view (WFC3/IR images).   The fact that this fit is not viable stems from the fact that it was an 'rscale' fit, yet it still thought only 2 sources was good enough for a viable fit, which may be mathematically sound, but typically not correct in practice as this example demonstrates.

**Comment by mcara** [comment]
I will study this. `nmatches` has no idea what was used for the fit - that is correct. It reports how many sources were matched during the "match" stage.

Take a look at the documentation for `fit_info` and specifically for the `fitmask` field, see documentation [`fit_wcs`](https://tweakwcs.readthedocs.io/en/stable/imalign.html#tweakwcs.imalign.fit_wcs) or [`iter_linear_fit`](https://tweakwcs.readthedocs.io/en/stable/linearfit.html#tweakwcs.linearfit.iter_linear_fit).

> `'fitmask`: A boolean array indicating which source positions where used for fitting (`True`) and which were clipped out (`False`). NOTE: For weighted fits, positions with zero weights are automatically excluded from the fits.

Then you can get the actual number of used (for the fit) sources as: `np.count_nonzero(fit_info['fitmask'])`.

**Comment by mcara** [comment]
And iterative fit always checks not to drop below `minobj` so if you do not think that 2 sources are enough to an `rscale` fit - simply specify the desirable number of sources to be used. I do not understand what is the issue with the number of sources.

**Comment by stsci-hack** [comment]
We are not concerned so much about how to control the number of sources used for a fit, but rather (at this point) simply responding to how many ended up being used.  Your suggestions for controlling the number of sources that should be used will be useful as well, but that is not the point of this issue.  This was submitted purely to point out the (apparent?) inconsistency between the values reported in the 'fit_info' dict based on the names of the keys.

**Comment by mcara** [comment]
Then 
```python
np.count_nonzero(fit_info['fitmask'])
```
as explained in https://github.com/spacetelescope/tweakwcs/issues/149#issuecomment-995378533 should give you exactly what you need.

**Comment by mcara** [comment]
I think we can close this issue.
