### ISSUE TITLE
align_wcs should have clip_accum from iter_linear_fit exposed

### ISSUE THREAD

**Issue by Vb2341** [spacetelescope/tweakwcs#168]
When attempting to align images with the JWST pipeline (a custom TweakRegStep), it can be difficult to get decent alignments when working in very dense fields (e.g. galaxies with resolved stars/clusters).  When looking at the residuals after attempting to align some NIRCAM images to HST catalogs (a very common use case I imagine), it's apparent that there are definitely outliers throwing off the fits.  Increasing the number of `nclip` iterations often doesn't fix this, as the bad matches are not cumulatively rejected.  It should be noted that the catalogs themselves aren't the issue here.  I checked them visually and there are certainly obvious matches.

In fact, this can lead to "circular" rejection, where I believe the rejected points oscillate between iterations.  I did a quick test where I set `nclip=15` and another with `nclip=350`, and when I extracted the fit residuals the results were largely the same.  In these cases, the variance does not appear to converge between iterations (I didn't test this explicitly, but 350 iterations seemed like enough), which leads to more false matches persisting into the final alignment, and leading to RMS's >1 pixel.  The only thing that really helped at all was setting sigma to some tiny value, like `0.35`, but that is obviously impractical for real use.  Setting the `tolerance` to anything above 0.5 basically forces the RMS to stay well above a few pixels too (and the issue isn't really the tolerance or sigma anyway)

When setting `clip_accum` in `iter_linear_fit` to True, the RMS's dropped by ~a factor of 10, and visually the alignments looked good.

Unfortunately `align_wcs` (and the method it calls in the various `WCSImageCatalog` classes in wcsimage) do not have this keyword argument exposed, so it requires a decent amount of work to use this functionality.  It would probably be useful to add this in the spec for the tweakreg step in the pipeline too, as this could likely be a problem aligning to Gaia as well.

It might even just be simpler to flip this switch to `True` by default, rather than `False`, though that might have other unforseen ramifications, especially on the default pipeline products for both HST and JWST and I figure setting it to `False` will be useful in many cases..  FWIW, all the other common sigma clipping I've run into _do_ accumulate the bad points by default (astropy sigma_clip, scipy.stats sigmaclip, and even drizzlepac's tweakreg).

If necessary, I can provide some test data/plots.  The code I'm using effectively just replaces the gaia alignment step with a user supplied catalog, so wouldn't be hard to get that working, to replicate the issue, but it isn't just the vanilla pipeline.

**Comment by mcara** [comment]
Looks like I implemented `clip_accum` but I forgot why... 🤣 In reality, this is a new mode of clipping, different from what is in HST's `drizzlepac`. I thought it would be useful but I was waiting for demand in order to complicate API.

**Comment by mcara** [comment]
I will think about how to do this. It just may take a little bit of time with other issues of higher priority.

**Comment by Vb2341** [comment]
No worries!  I see the code is different, so I understand that it's not apples to apples.  In the meantime I've edited my copy so that it's always on, so at least we'll see if that causes any catastrophic issues 🤷 .
