### ISSUE TITLE
Out-of-Memory error encountered somewhere in align_wcs step

### ISSUE THREAD

**Issue by keflavich** [spacetelescope/tweakwcs#181]
I've encountered this out-of-memory error in the middle of a JWST pipeline run:
```
2023-06-21 22:16:16,818 - stpipe.Image3Pipeline.tweakreg - INFO - ***** tweakwcs.imalign.align_wcs() ended on 2023-06-21 22:16:16.818759
2023-06-21 22:16:16,818 - stpipe.Image3Pipeline.tweakreg - INFO - ***** tweakwcs.imalign.align_wcs() TOTAL RUN TIME: 0:12:34.538185
2023-06-21 22:16:16,818 - stpipe.Image3Pipeline.tweakreg - INFO -
2023-06-21 22:16:17,647 - stpipe.Image3Pipeline.tweakreg - INFO -
2023-06-21 22:16:17,647 - stpipe.Image3Pipeline.tweakreg - INFO - ***** tweakwcs.imalign.align_wcs() started on 2023-06-21 22:16:17.647285
2023-06-21 22:16:17,647 - stpipe.Image3Pipeline.tweakreg - INFO -       Version 0.8.1
2023-06-21 22:16:17,647 - stpipe.Image3Pipeline.tweakreg - INFO -
2023-06-21 22:25:15,719 - stpipe.Image3Pipeline.tweakreg - INFO - Aligning image catalog 'GROUP ID: 987654' to the reference catalog.
2023-06-21 22:25:16,031 - stpipe.Image3Pipeline.tweakreg - INFO - Matching sources from 'jw02221001001_03101_000' catalog with sources from the reference 'Unnamed' catalog.
2023-06-21 22:25:16,031 - stpipe.Image3Pipeline.tweakreg - INFO - Computing initial guess for X and Y shifts...
/tmp/slurmd/job349664/slurm_script: line 4:  5070 Killed                  /blue/adamginsburg/adamginsburg/miniconda3/envs/python39/bin/python /blue/adamginsburg/adamginsburg/jwst/brick/reduction/PipelineRerunNIRCAM-LONG.py --filternames=F405N
slurmstepd: error: Detected 1 oom-kill event(s) in StepId=349664.batch. Some of your processes may have been killed by the cgroup out-of-memory handler.
```

I was running on a fairly straightforward set of NIRCAM long-wavelength observations with 48 independent exposures on a machine with 256GB RAM, which I think should be more than enough for any conceivable image operations.  I used my own custom catalog based on a different NIRCAM image.

I'm trying to work around this by reducing the `brightest` parameter, but I'm not sure that's the memory bottleneck.  Is it possible `geomap` is making some gigantic n x n x n matrix?

**Comment by orifox** [comment]
Hi @keflavich I've actually found that I need a 500GB machine for a couple of my observation runs. We now have one configured at STScI. Do you have that capability at your host institution? Even for the short term, so you can at least test out the hypothesis.

The thing is that's not where I usually see a break down in the process. I am sure others on this github can help you dig deeper, but another option to try is to break your data up into fewer exposures to see what happens. I'll keep thinking about this.

**Comment by keflavich** [comment]
Thanks @orifox .  I've also found that some steps require 500 GB, but only for short wavelength previously (bigger images).

I haven't narrowed it down yet, but I suspect this:
https://github.com/spacetelescope/tweakwcs/blob/master/tweakwcs/matchutils.py#L282-L283
is the culprit; outer products can be arbitrarily large and my reference catalog may be huge.

**Comment by keflavich** [comment]
OK I confirmed those lines are the problem.  I added a debug line, and it's trying to create at least two 240k x 64k images, which if they're float64, comes to 230 GB.  
```
2023-06-22 15:24:47,290 - stpipe.Image3Pipeline.tweakreg - INFO - in _xy_2dhist.  imgxy.shape:(240000, 2), refxy.shape:(64845, 2)
/tmp/slurmd/job405914/slurm_script: line 4: 38612 Killed                  /blue/adamginsburg/adamginsburg/miniconda3/envs/python39/bin/python /blue/adamginsburg/adamginsburg/jwst/brick/reduction/PipelineRerunNIRCAM-LONG.py --filternames=F466N
slurmstepd: error: Detected 1 oom-kill event(s) in StepId=405914.batch. Some of your processes may have been killed by the cgroup out-of-memory handler.
```

This little snippet could be made a lot more memory efficient, but probably it's more important that users be warned that this can happen.

I'll propose some small changes, but my conclusion here is that I should be using a higher S/N threshold and maybe trim down my catalog by a factor of a few.

**Comment by mcara** [comment]
Image size is irrelevant to the catalog matching. The catalog size is important.

```
INFO - Matching sources from 'jw02221001001_03101_000' catalog with sources from the reference 'Unnamed' catalog.
```

How large are the catalogs `'jw02221001001_03101_000'` and `'Unnamed'`?

**Comment by mcara** [comment]
Also, `tweakwcs` relies on `stsci.stimage` which supplies the `xyxymath` algorithm for catalog matching. If anything - the fix should be there.

**Comment by keflavich** [comment]
> Image size is irrelevant to the catalog matching. The catalog size is important.

yes, the variable name should be `imgxy` - it's the list of catalog coordinates in the image frame, iiuc.

And yes, I agree, that is the right place for the fix I propose.  It took me a while to find that, though, and probably the catalog size check makes sense even at a higher level.  It is unlikely for a field to have (or need) >200,000 sources for JWST or HST pointing solutions.

The catalogs were ~240k and ~60k.  I changed my SNR threshold and now the catalogs are down to a manageable size.

**Comment by keflavich** [comment]
I had said "and it's trying to create at least two 240k x 64k images", which is true as I understand it - the catalogs were size 240k and 60k, and the outer product is therefore trying to create images (2D arrays) that shape.

**Comment by mcara** [comment]
Default value for the `brightest` is 200 which is designed to prevent such situations.

**Comment by keflavich** [comment]
I have brightest set to 5000.  It's still passing 240,000 sources on to be fit downstream.  Is this a bug, then?

**Comment by keflavich** [comment]
I see that `brightest` is passed on to DAOStarFinder, so if it's a bug, it's downstream in photutils.

**Comment by keflavich** [comment]
I'll investigate this further; I have tested independently that `DAOStarFinder` respects the `brightest` keyword.

**Comment by keflavich** [comment]
The step with >100k sources is toward the end of the tweakreg pipeline step.  It's happening at the absolute reference catalog matching.  In this case, all of the sources from all of the individual images are being combined into one giant catalog that is then crossmatched to the reference catalog.

https://github.com/spacetelescope/jwst/blob/04332ea239a261ccedb1cf423efe49db47e1b57b/jwst/tweakreg/tweakreg_step.py#L440-L451

So you're right, the defaults for JWST's tweakreg should avoid this, but there's no stopping users like me.
