### ISSUE TITLE
NumPy 2.0 compatiblity

### ISSUE THREAD

**Issue by WilliamJamieson** [spacetelescope/tweakwcs#186]
Currently `tweakwcs` makes use of `np.sctypes`, https://github.com/spacetelescope/tweakwcs/blob/a9bf1b1758024980cfc5a2a2af2369e8c52b0562/tweakwcs/linalg.py#L59 which will be removed by NumPy 2.0 (see #24376) as part of the NumPy's [NEP 52](https://numpy.org/neps/nep-0052-python-api-cleanup.html) efforts. This issues is preventing the testing of `romancal` for NumPy 2.0 compatiblity, see this [CI run](https://github.com/spacetelescope/romancal/actions/runs/6148621015/job/16682731003?pr=840#step:10:1121). In order to continue NumPy 2.0 test, `romancal` needs an upstream fix in `tweakwcs` to resolve this problem.

Additionally, in will be advantageous for `tweakwcs` to begin testing for NumPy 2.0 compatibility now and resolving and deprecated or removed functionality related to it ahead of the NumPy 2.0 release.

**Comment by mcara** [comment]
Fixed via #185
