### ISSUE TITLE
Extraneous output to stdout

### ISSUE THREAD

**Issue by stsci-hack** [spacetelescope/tweakwcs#58]
Output from tweakwcs now (as of v.0.4.0) includes reporting the names of the keys for the tpwcs object.  Specifically, 

imalign.py:582:            print(wcat.tpwcs.meta.keys())
imalign.py:584:            print(wcat.tpwcs.meta.keys())

These do not hinder the operation of the code, but certainly clutter the output messages and may confuse the end user.

**Comment by mcara** [comment]
Ah, these are leftovers ... Sorry, I'll fix it.

**Comment by mcara** [comment]
Fixed via #59
