### ISSUE TITLE
variable not always initialized when using 2dhist mode

### ISSUE THREAD

**Issue by stsci-hack** [spacetelescope/tweakwcs#89]
Testing of the new alignment code in drizzlepac uncovered another edge case for the 2dhist mode; namely, 
    
`
tweakwcs.align_wcs(imglist, reference_catalog, match=match, expand_refcat=False) 
`
 `File "/user/hack/dev/miniconda3/envs/rthstdev/lib/python3.6/site-packages/tweakwcs/imalign.py", line 570, in align_wcs`
`    sigma=sigma`
`  File "/user/hack/dev/miniconda3/envs/rthstdev/lib/python3.6/site-packages/tweakwcs/wcsimage.py", line 1129, in align_to_ref`
`    match=match`
`  File "/user/hack/dev/miniconda3/envs/rthstdev/lib/python3.6/site-packages/tweakwcs/wcsimage.py", line 767, in match2ref`
`    mref_idx, minput_idx = match(refcat.catalog, self._catalog)`
`  File "/user/hack/dev/miniconda3/envs/rthstdev/lib/python3.6/site-packages/tweakwcs/matchutils.py", line 252, in __call__`
`    searchrad=self._searchrad`
`  File "/user/hack/dev/miniconda3/envs/rthstdev/lib/python3.6/site-packages/tweakwcs/matchutils.py", line 336, in _estimate_2dhist_shift`
`    .format(xp, yp, sig, flux))`
`UnboundLocalError: local variable 'sig' referenced before assignment`

This appears to happen in the edge/error case when zpmat_mask is all zero.

**Comment by mcara** [comment]
Thanks! Indeed this is a bug.

**Comment by mcara** [comment]
Fixed via #90
