### ISSUE TITLE
Serialization of jwst wcs fails due to circular inverse definition

### ISSUE THREAD

**Issue by mcara** [spacetelescope/tweakwcs#97]
https://github.com/spacetelescope/tweakwcs/blob/98b7f9aea69b347375a86f834da939ed81b0764c/tweakwcs/tpwcs.py#L684-L685

Due to the lines above, serialization in `asdf` fails.

```python
import asdf
import gwcs
import tweakwcs
from jwst.datamodels import ImageModel
d = ImageModel('jw42424001001_01101_00001_nrcb5_cal.fits')
tpwcs = tweakwcs.tpwcs.JWSTgWCS(d.meta.wcs, {'v2_ref': 0, 'v3_ref': 0, 'roll_ref': 0})
tpwcs.set_correction()
asdf.AsdfFile({'wcs': tpwcs.wcs})
```
This results in
```
RecursionError: maximum recursion depth exceeded in __subclasscheck__
```
This recursive definition is supported by modeling and Python. Should it not be supported by `asdf`?

CC: @perrygreenfield @nden @eslavich

**Comment by mcara** [comment]
Instead of your example, @jdavies-st , https://github.com/spacetelescope/jwst/pull/4491#issuecomment-579935712, let's consider this:

```python
from astropy.modeling.models import Mapping, Identity, Const1D
c2tan = ((Mapping((0, 1, 2), name='xyz') /
          Mapping((0, 0, 0), n_inputs=3, name='xxx')) |
         Mapping((1, 2), name='xtyt'))
tan2c = (Mapping((0, 0, 1), n_inputs=2, name='xtyt2xyz') |
         (Const1D(1, name='one') & Identity(2, name='I(2D)')))
c2tan.inverse = tan2c
```

What about inverse of `tan2c `? Shouldn't it have an inverse?

In other words, let's say user somehow retries "a model" formed by:

```
m = c2tan.inverse
```
Shouldn't this model have an inverse?

**Comment by mcara** [comment]
Defining the inverses in a clean way was possible in the `TPCorr` but how do I define a custom inverse in a _compound_ model?

**Comment by jdavies-st** [comment]
The inverse of an inverse (recursion ad infinitum) is halted when the inverses are auto-defined.  But if you explicitly define them, then all bets are off and you get these sorts of errors.

The inverse never needs a custom inverse I believe.  The inverse of the custom inverse is the original transform itself.

The inverse of `c2tan.inverse` is `c2tan`.

**Comment by mcara** [comment]
But how does an user know whether an inverse is "auto-defined" or "user"-defined? Should they not all behave the same way _to the user_?

> The inverse of `c2tan.inverse` is `c2tan`.

I know that. But can an user know that without looking into the code that defined `c2tan`?

**Comment by mcara** [comment]
The point here is that if let's say `tan2c` is a transformation in a `gwcs` pipeline going from `'frame1'` to `'frame2'`, and user does something like `t = WCS. get_transform('frame2', 'frame1')`, should the user be able to do `t.inverse` or not? Is this supposed to work or this is not supported even when _we know what the inverse transformation is_?

**Comment by mcara** [comment]
Why does user need to worry about how an inverse is defined at all? Shouldn't the formalism just support that? And it _does_! The only thing that seems not to work is serialization.

**Comment by perrygreenfield** [comment]
This is new code that causes the problem? I'd like to understand the context.

**Comment by perrygreenfield** [comment]
Presumably the solution is for ASFD to place a reference in the second case to break the circularity as far as serialization goes (not that I've given this deep thought(TM) though). If this is the case, the trick is where to recognize that a reference is needed. Very naively it would seem that ASDF should keep a registry of all previous objects serialized (including those in the process of serialization, and should it encounter the identical object again (identical; equality is not sufficient), a reference is generated). I think I talked to Mike or Dan about this at one point but I don't think it was implemented, but I may be wrong. @eslavich , any thoughts?

If this is a significant amount of work, @mcara do you have any work arounds in the meantime?

**Comment by mcara** [comment]
Let's say:
```
from asdf import AsdfFile
from astropy.modeling.models import Mapping, Identity, Const1D
c2tan = ((Mapping((0, 1, 2)) / Mapping((0, 0, 0), n_inputs=3)) | Mapping((1, 2)))
tan2c = (Mapping((0, 0, 1), n_inputs=2) | (Const1D(1) & Identity(2)))
c2tan.inverse = tan2c
# tan2c.inverse = c2tan
# AsdfFile({'c2tan': c2tan})
w = WCS([('frame1', c2tan), ('frame2', None)])
t = w.get_transform('frame2', 'frame1')
```
In this example, imagine `w` is loaded by user from an asdf file. Should the user be able to do `t.inverse` without understanding whether the transformation has an "auto-inverse" or a "user" inverse? Should I even provide this inverse especially that I know what it is or should I just return `None` because it would result in a circular definition?

**Comment by mcara** [comment]
> If this is a significant amount of work, @mcara do you have any work arounds in the meantime?

In the meantime, _I think_, we could live without inverse of an inverse being available.

**Comment by perrygreenfield** [comment]
@mcara do you have an example where the user wouldn't realize that mod.inverse inverse is mod?

**Comment by mcara** [comment]
@perrygreenfield 

> @mcara do you have an example where the user wouldn't realize that mod.inverse inverse is mod?

Funny ... at first glance 😄 But... Are you suggesting that in the example from https://github.com/spacetelescope/tweakwcs/issues/97#issuecomment-579979199 user should do:

```python
t_inv = t = w.get_transform('frame1', 'frame2')
```
instead of `t.inverse`???

**Comment by mcara** [comment]
@perrygreenfield That is, let's consider this:

```
w = WCS([('frame1', c2tan), ('frame2', None)])

t12 = w.get_transform('frame1', 'frame2')
t12_inv = t12.inverse  # this works

t21 = w.get_transform('frame2', 'frame1')
t21_inv = t21.inverse  # this does not work; instead user should do:
t21_inv = w.get_transform('frame1', 'frame2')
```
Is it OK for this kind of asymmetric behavior? Assume user knows nothing about `t12`. Should the user attempt `t21_inv = t21.inverse` or should the user magically know that `t21_inv = w.get_transform('frame1', 'frame2')`?

**Comment by perrygreenfield** [comment]
In the first example above, I'm not sure what the intended user interface of gwcs is regarding inverting frames (I'm not sure I've thought about or if I did, I forgot) in using get_transform. If the user knows the order of frames, they can do  t22 = get_transform('frame1', 'frame2').inverse as you note in the second comment immediately preceding.

I think the user can easily see the order of frames in the WCS definition so I don't think it is opaque to them. I do agree it would be nice to be completely symmetric, but I'm not sure it is urgent to solve (it is a worthy goal though and we should make it an ASDF issue if isn't already).
Any comments @nden ?

**Comment by mcara** [comment]
@perrygreenfield Even if user know all of that, how does the user know that _it is `t21`_ (not `t22` 😄  - that's `Identity`) that does not have an inverse through `.inverse` but has it through `get_transform` and not the forward transformation `t12`. That is, how is the user to know when a transformation is the "weird" one?

Let's say a function works with a `gwcs` object and returns a transformation - the `t21` one. How is the "user" who receives such an object can find its inverse?

**Comment by mcara** [comment]
A temporary workaround is to disable inverses. But is this cannot be fixed in `ASDF`, then probably the best would have been to just keep `TPCorr`.

**Comment by eslavich** [comment]
@perrygreenfield the tree-walking function does attempt to handle recursive loops, but in this case it's thwarted by the fact that astropy is itself calling the tree-walking function, which causes asdf to lose the context that is tracking object ids.  We could add something like this:

```python
with yamlutil.context():
  tagged_tree = yamlutil.custom_tree_to_tagged_tree(tree, self)
```
that would cause every call within the context manager to use the same set of previously encountered object ids.

**Comment by eslavich** [comment]
Would be more annoying if thread-safety is an issue...

**Comment by perrygreenfield** [comment]
Thread safety is often an annoyance :-)

@mcara I'm not sure what you mean by disabling inverses. They are fine to use with original direction of the transform. As far as a user getting a transform from a function, I suppose, but I also suppose for the time being the function that is getting it from gwcs (presumably written by someone else) could define it for them (of course, making it unserializable if the user tries that, a problem in the longer run, but probably not one going to be faced in the next year since not many are currently serializing it outside the pipeline that aren't familiar with ASDF.

And perhaps it isn't too difficult to fix as @eslavich suggests.

**Comment by mcara** [comment]
> what you mean by disabling inverses

**Comment by mcara** [comment]
Oh, all these buttons...

> what you mean by disabling inverses

I mean "not providing inverse of an inverse".

**Comment by nden** [comment]
To address some of the issues above:

- `WCS.forward_transform` returns the entire transform in the forward direction.
- `WCS.available_frames` returns a list of frames in the order of the forward direction.
So `ft = WCS.get_transform("frame1"m, "frame2")` returns the forward transform and `ft.inverse` is its inverse. 

I think in general, for any transform, defining one inverse isprobably sufficient. Otherwise where should we stop in the chain of inverses?

**Comment by mcara** [comment]
> Otherwise where should we stop in the chain of inverses?

I do not think we should.

**Comment by mcara** [comment]
I believe this was fixed via https://github.com/asdf-format/asdf/pull/777
